name: My Java App Workflow (Docker)

on: 
  workflow_dispatch:
    inputs:
      UploadToRegistry:
        description: "Upload to Registry"
        required: true
        default: false
        type: boolean
jobs:
  build:
    runs-on: Windows

    steps:
    - name: Checkout application
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Application
      run: mvn clean package
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: my-java-application-1.0-SNAPSHOT.jar
        path: target

  docker:
    runs-on: Windows
    if: ${{ github.event.inputs.UploadToRegistry == 'true' }}
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v5.0.0
      with:
        name: my-java-application-1.0-SNAPSHOT.jar

    - name: Github registry login
      
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: 'charanaswanth'
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run:
        docker build -t ghcr.io/${{ github.repository_owner }}/myjavapp:${{ github.run_number }} .

    - name: Aqua Security Trivy
      uses: aquasecurity/trivy-action@0.32.0
      with:
        image-ref: ghcr.io/${{ github.repository_owner }}/myjavapp:${{ github.run_number }}              

    #- name: Push Docker image
    #  run:
    #      docker push ghcr.io/${{ github.repository_owner }}/myjavapp:${{ github.run_number }}
